---
output:
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
    number_sections: true
  bookdown::word_document2:
    reference_docx: "template_CHN.docx"
    keep_md: true
    number_sections: FALSE
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_format = c("bookdown::word_document2", "bookdown::pdf_document2")) })
documentclass: ctexart

fontsize: 12pt
geometry: margin=1in
# bibliography: /Users/sunyufei/Desktop/Zotero.bib
csl: "paper/china-national-standard-gb-t-7714-2015-author-date.csl"
link-citations: true
colorlinks: true
toc: false

editor_options: 
  markdown: 
    wrap: sentence

title: '能力不够压力来凑：数字治理能力下的压力型体制'
subtitle: "——基于Covid19期间的春节返乡政策的混合方法研究"

author:
- 孙宇飞^[清华大学政治学系博士生，联系电话：18638750921，邮箱：sunyf20@mails.tsinghua.edu.cn]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
if (!require(pacman)) install.packages("pacman")
library(pacman)
p_load(grid,
       gridExtra,
       png,
       magick, 
       usmap,
       interplot,
       dotwhisker,
       modelsummary,
       # Visualization
       lubridate,
       # Applied
       broom,
       knitr,
       # dependency
       scales,
       tidyverse,
       drhutools,
       qs)
set.seed(19970921)
# Theme setup
theme_set(theme_minimal())
#Data input
```

```{R CrawlerPolicy, eval = FALSE}
citycode <- read_html("http://www.bendibao.com/index.htm") %>% 
  html_nodes("#city-list a") %>% 
  html_attrs()
cityname <- read_html("http://www.bendibao.com/index.htm") %>% 
  html_nodes("#city-list a") %>% 
  html_text()
CityForce <- as.data.frame(cityname)
CityForce$citycode <- CityForce$cityname
a <- 1
for (c in citycode){
  CityForce$citycode[a] <- c
  a <- a + 1
  print(c)
}

CityForce$duplicated <- duplicated(CityForce$cityname)

CityForce <- CityForce %>% 
  dplyr::filter(duplicated != TRUE) %>% 
  dplyr::filter(citycode != "http://kunshan.bendibao.com/") %>% 
  dplyr::filter(citycode != "http://hk.bendibao.com/") %>% 
  dplyr::filter(citycode != "http://am.bendibao.com/") %>% 
  dplyr::select(-duplicated)

CityForce$citycode[8] <- "http://tj.bendibao.com/"
CityForce$citycode[9] <- "http://cq.bendibao.com/"
CityForce$citycode[92] <- "http://zz.bendibao.com/"
CityForce$citycode[257] <- "http://dl.bendibao.com/"

a <- 1
for (c in CityForce$citycode){
forcehtml <- read_html(paste0(c, "news/gelizhengce/all.php?leavecity=hk"), encoding = "UTF-8")
forcetext <- forcehtml %>% 
  html_nodes(".list-primary-item+ .list-primary-item .result") %>% 
  html_text()
CityForce$ForceText[a] <- forcetext
a = a + 1
print(c)
}

DGDI <- read.csv("/Users/sunyufei/Desktop/DGDI.csv")

n <- 1
while (n <= length(DGDI$CityNameChinese)) {
  DGDI$RegionCode[n] <- regioncode::regioncode(DGDI$CityNameChinese[n], 2019, 2019, "name2code")
  n <- n + 1
  print(n)
}

data <- read.csv("/Users/sunyufei/Desktop/ConfirmedCases.csv")

n <- 1
while (n <= length(data$CityName)) {
  data$CityCode[n] <- regioncode::regioncode(data$CityName[n], 2019,2019,"name2code",incompleteName = "from")
  n <- n + 1
  print(n)
}

data$url <- paste0("https://news.sina.cn/project/fy2020/yq_province.shtml?city=CN",data$CityCode,"00000000")

write_csv2(data, "data/IV/Upper_government_pressure/ConfirmedCases/ConfirmedCases.csv")

qsave(CityForce, './data/foecetext20210206.qs')
write.xlsx(CityForce, './data/foecetext20210206.xlsx')
# 2021.2.6手动更新数据，补充数据分为三类：灰色标注，县级市，删去之即可；黄色标注，已补充，请更新；红色标注，没有明确的防疫信息
# 请注意，拉萨市已更新隔离政策，请重新标注；
# 请注意，新疆自治区除乌鲁木齐、昌吉明确隔离政策和几个地级市完全没有发布政策外，其他地市均为搪塞政策，我们要单独分类或致电当地卫健委查询
```

```{R datacleaning}
# ForceCodeing1 <- read.csv("data/DV/Team1/ForceCoding.csv", header = TRUE)
# n <- 1
# for(i in 1:length(ForceCodeing1$CityName)){
#   if (max(ForceCodeing1[n,][3:7]) > 0){
#     ForceCodeing1$force[n] <- 1
#   }
#   if (ForceCodeing1$"报告.报备"[n] > 0){
#     ForceCodeing1$force[n] <- 2
#   }
#   if (max(ForceCodeing1[n,][10:13]) > 0){
#     ForceCodeing1$force[n] <- 3
#   }
#   if (max(ForceCodeing1[n,][18:19]) > 0){
#     ForceCodeing1$force[n] <- 4
#   }
#   if (max(ForceCodeing1[n,][16:17]) > 0){
#     ForceCodeing1$force[n] <- 5
#   }
#   if (ForceCodeing1$集中隔离[n] > 0){
#     ForceCodeing1$force[n] <- 6
#   }
#   print(n)
#   n <- n + 1
# }
# 
# ForceCodeing2 <- read.csv("data/DV/Team2/ForceCoding.csv", header = TRUE)
# n <- 1
# for(i in 1:length(ForceCodeing2$CityName)){
#   if (max(ForceCodeing2[n,][3:7]) > 0){
#     ForceCodeing2$force[n] <- 1
#   }
#   if (ForceCodeing2$"报告.报备"[n] > 0){
#     ForceCodeing2$force[n] <- 2
#   }
#   if (max(ForceCodeing2[n,][10:13]) > 0){
#     ForceCodeing2$force[n] <- 3
#   }
#   if (max(ForceCodeing2[n,][18:19]) > 0){
#     ForceCodeing2$force[n] <- 4
#   }
#   if (max(ForceCodeing2[n,][16:17]) > 0){
#     ForceCodeing2$force[n] <- 5
#   }
#   if (ForceCodeing2$集中隔离[n] > 0){
#     ForceCodeing2$force[n] <- 6
#   }
#   print(n)
#   n <- n + 1
# }
# 
# Recheck <- left_join(ForceCodeing1, ForceCodeing2, by = c("CityName", "CityCode"))
# Recheck$W <- Recheck$force.x - Recheck$force.y
# 
# ForceText <- read_csv("data/DV/ForceText.csv") %>% 
#   dplyr::select(cityname, ForceText) %>% 
#   dplyr::rename(CityName = cityname)
# 
# Recheck <- Recheck %>% 
#   dplyr::left_join(ForceText)
# 
# write_csv2(Recheck, "data/DV/Recheck.csv")

ForceCoding_Province <- read.csv("data/DV/ForceCoding_Province.csv")

ForceCodeing <- read_csv("data/DV/ForceCodingCorrected.csv") %>% 
  dplyr::select(CityCode, Correct) %>% 
  dplyr::rename(Force = Correct, RegionCode = CityCode)

ablity <- read_csv("data/IV/Digital_governance_capabilities/DGDI.csv")

fulldata <- ablity %>% 
  dplyr::left_join(ForceCodeing)
  
ConfirmedCases_Province <- read.csv("data/IV/Upper_government_pressure/ConfirmedCases/ConfirmedCases_Province.csv") %>% 
  dplyr::rename(ConfirmedCases20210101_Province = ConfirmedCases20210101, ConfirmedCases20210131_Province = ConfirmedCases20210131)

ConfirmedCases_City <- read.csv("data/IV/Upper_government_pressure/ConfirmedCases/ConfirmedCases.csv") %>% 
  dplyr::select(-url) %>% 
  dplyr::rename(RegionCode = CityCode, ConfirmedCases20210101_City = ConfirmedCases20210101, ConfirmedCases20210131_City = ConfirmedCases20210131)

ConfirmedCases <- ConfirmedCases_Province %>% 
  dplyr::left_join(ConfirmedCases_City) %>% 
  dplyr::select(-CityName)

ConfirmedCases$ConfirmedCases_Period_City <- ConfirmedCases$ConfirmedCases20210131_City - ConfirmedCases$ConfirmedCases20210101_City
ConfirmedCases$ConfirmedCases_Period_Province <- ConfirmedCases$ConfirmedCases20210131_Province - ConfirmedCases$ConfirmedCases20210101_Province

fulldata <- fulldata %>% 
  dplyr::left_join(ConfirmedCases) %>% 
  dplyr::left_join(ForceCoding_Province)

fulldata$load <- fulldata$Force - fulldata$ForcecodingProvince

population_movement <- read.csv("data/CV/population_movement.csv")

fulldata <- fulldata %>% 
  dplyr::left_join(population_movement, by = "CityNameChinese")

baidu_index <- read_csv("data/IV/Baidu_Index.csv")

baidu_index$trend202012202101_covid19 <- baidu_index$trend20201231_covid19 + baidu_index$trend20210131_covid19

fulldata <- fulldata %>% 
  dplyr::left_join(baidu_index)

citydata <- read_csv("data/IV/citydata.csv") %>% 
  dplyr::rename(RegionCode = CityCode)

fulldata <- fulldata %>% 
  dplyr::left_join(citydata)

dijishi <- fulldata %>% 
  dplyr::filter(cityclass == 1)

dijishi <- dijishi %>% 
  dplyr::group_by(ProvinceCode) %>% 
  dplyr::mutate(peer_pressure = mean(ConfirmedCases_Period_City))
  
shenghuichengshi <- fulldata %>% 
  dplyr::filter(cityclass == 2)

shenghuichengshi$peer_pressure <- mean(shenghuichengshi$ConfirmedCases_Period_City)

zhixiashi <- fulldata %>% 
  dplyr::filter(cityclass == 3)

zhixiashi$peer_pressure <- mean(zhixiashi$ConfirmedCases_Period_City)

fulldata <- rbind(dijishi, shenghuichengshi, zhixiashi)

qsave(fulldata, "data/paperdata.qs")

model <- glm(load ~ 治理能力 + `医院、卫生院床位数_全市_张` + ConfirmedCases_Period_City + ConfirmedCases_Period_Province + diff202012Covid + peer_pressure + 地区生产总值增长率_全市_百分比 + 年末总人口_全市_万人, family = poisson(link = "log"), data = fulldata)
summary(model)

```

这是政治表态，所以要把压力体现方式分为几个维度，比如政治表态；具体措施；会议频度；领导人出现情况。然后根据自己掌握的材料，来说明选取了哪几个维度来测量。在这里压力就是“政令的统一和落实”

- Level
  - 1 = 基本通行政策（测体温、健康码、健康告知书、健康问询、健康提醒）
  - 2 = 健康报备
  - 3 = 核酸检测/抗体检测
  - 4 = 健康监测
  - 5 = 居家隔离
  - 6 = 集中隔离

# 文章分析逻辑

政策加码过程：中央 - 省 - 地级市 - 基层

政策加码主体：下一级政府

中央 - **省**：公开政策比较

省 - **地级市**-政策的层面：公开政策比较

省 - **地级市**-执行的层面：公开政策与政务留言板的数值差异比较


# 分析模型

政策加码量（地级市） ~ 地级市数字治理能力 + 上级政府压力 + 同级政府压力 + 民众压力 + 上级政府明令禁止“层层加码” + 其他控制变量

- 分析单位：中国大中城市101（副省级和省会城市33 + 普通大中城市68）

- 变量测量
  - 因变量：政策加码量
    - 政策层面
      - 地级市政策 - 省级政策
      - 地级市政策
    - 执行层面
      - 政务留言板的相对数量
      - 政务留言板的相对情绪
  - 自变量
    - 核心自变量：地级市数字治理能力（2020数字政府发展指数报告）
    - 上级政府压力
      - 上级政府开会的次数（全么？准么？）
      - 政府工作报告中提及的关键词数量（成果越好的提的越多？）
      - 该省的确诊人数
      - 该省的经济发展水平
    - 同级政府压力
      - 其他同级城市（省会和副省级城市/同省普通大中城市）的确诊数量
      - 其他同级城市（省会和副省级城市/同省普通大中城市）的政策严格程度
      - 经济差值和差值在省内的排名
    - 民众压力
      - 政府留言板的数量/情绪？
    - 上级政府明令禁止“层层加码”
    - 其他控制变量
      - 人口流动
      - 经济发展
      - 疫情变量
      - 时间控制变量
      
      
# Codebook

## 地方政策标签: 编码规则

.small[本节会逐个变量的进行介绍]

- 1-6 测体温、健康码、健康告知书、健康问询、健康提醒、报告/报备
  - 有规定 = 1
  - 没有规定 = 0
  
- 7 提前报备时间
  - 规定报备且有明确天数 = 直接填写提前报备的天数（单位：天）
  - 规定报备但无明确天数 = 1
  - 没有规定报备 = 0
  
- 8 进入前核酸检测（持核酸检测阴性证明）
  - 有规定 = 1
  - 没有规定 = 0

- 9 进入前核酸检测时间
  - 规定核酸检测且有明确天数 = 直接填写提前核酸检测天数（单位：天）
  - 规定核酸检测但无明确天数 = 7
  - 没有规定核酸检测 = 0

- 10 进入后核酸检测
  - 有规定 = 1
  - 没有规定 = 0
  
- 11 进入后核酸检测次数
  - 规定核酸检测且有明确次数 = 直接填写
  - 规定核酸检测但无明确次数 = 1
  - 没有规定核酸检测 = 0

- 12 进入后核酸检测时间
  - 规定核酸检测且有明确天数 = 直接填写（单位：天）
  - 规定核酸检测但无明确天数 = 1
  - 没有规定核酸检测 = 0
  
- 13 血清学检测(血清抗体)
  - 有规定 = 1
  - 没有规定 = 0

- 14 居家隔离(居家健康监测)
  - 有规定 = 1
  - 没有规定 = 0

- 15 居家隔离时间
  - 规定且有明确天数 = 直接填写（单位：天）
  - 规定但无明确天数 = 14
  - 无规定 = 0
  
- 16 社区健康监测（社区健康管理）
  - 有规定 = 1
  - 没有规定 = 0
  
- 17 社区健康监测时间
  - 规定且有明确天数 = 直接填写（单位：天）
  - 规定但无明确天数 = 14
  - 无规定 = 0

- 18 集中隔离
  - 有规定 = 1
  - 没有规定 = 0
  
- 19 集中隔离时间
  - 规定且有明确天数 = 直接填写（单位：天）
  - 规定但无明确天数 = 14
  - 无规定 = 0

- 20 特殊措施

# DV

- Factor Analysis?

- Time?
  - 测体温(1)
  - 健康码(1)
  - 健康告知书(1)
  - 健康问询(1)
  - 健康提醒(1)
  - 报告/报备(5)
  - 提前报备时间
  - 进入前核酸检测(60)
  - 进入前核酸检测时间
  - 进入后核酸检测(60)
  - 进入后核酸检测次数
  - 进入后核酸检测时间
  - 血清学检测(血清抗体)(60)
  - 居家隔离(360)
  - 居家隔离时间
  - 社区健康监测(720)
  - 社区健康监测时间
  - 集中隔离(1440)
  - 集中隔离时间
  - 特殊措施

- Level
  - 1 = 基本通行政策（测体温、健康码、健康告知书、健康问询、健康提醒）
  - 2 = 健康报备
  - 3 = 核酸检测/抗体检测
  - 4 = 健康监测
  - 5 = 居家隔离
  - 6 = 集中隔离

# 之后的研究展望

- 治理能力与压力转化的关系
- 政治距离与压力转化的关系（测量政治优先还是人民优先）
- 治理能力、文化特性与疫情防控有效性的关系（究竟是能力强还是民众更守纪律）。典型事件往往可以集中放大各种矛盾。这也是为什么现在一些学者用电影来较政治学、公共管理的原因。

      

